### PR TITLE
Support for OAuth Authentication

### PR DESCRIPTION
**Pull request by JonnyBoy333**
Great work on this extension, we are using it every day. I've added the ability to use OAuth authentication into the netsuiteRestClient.js file. With this functionality, if you don't specify the Authentication property in the settings options it will use the token settings properties instead and authenticate that way. The readme has also been updated with the added functionality.

Let me know if this is of interest to you or if you would like to see changes made to how it works.

### CODE REVIEW

**Comment by adman2002** [comment]
How did you get this to work in VSCode? If I just overwrite the script file, it wont load the extension. Did you have to create a new build locally?

**Comment by jorgeiriarte** [comment]
I also have the same question as adman2002. Is it possible to explain how to set it up?

**Comment by silverl** [comment]
I could use beta testers of the new 1.0.0 version in Github release tab. I tried but I think failed to get OAuth working, even though it looks like everything should work.

Would any of you be interested in reviewing the code?

**Comment by silverl** [comment]
OAuth  now fully supported as of v1.0.2.

https://github.com/netsuite-upload-org/netsuite-upload/releases/tag/v1.0.2

**Pull request closed without merging**
