### PR TITLE
Many many changes...

### PR DESCRIPTION
**Pull request by silverl**
Previously, it was necessary to right-click a file in the solution explorer.
Now we can push by executing the command via Ctrl-Shift-P. This also should allow mapping a hotkey to the Push command.

### CODE REVIEW

**Comment by wym89** [comment]
@silverl  on line 49 if you check if file is empty obj the ctrl+u shortcut will work
`        if (!file || !Object.keys(file).length) { }
`

**Comment by silverl** [comment]
@wym89 Would you post that with the surrounding lines please? I'm getting errors running the command via the command palette after making your suggested change. Thanks.

**Comment by wym89** [comment]
@silverl  here is the surounding lines
` let uploadFileDisposable = vscode.commands.registerCommand('netsuite-upload.uploadFile', (file) => {
       
        // Root SuiteScript folder has to be opened 
        if (!vscode.workspace.rootPath) {
            vscode.window.showErrorMessage(noProjectOpenedErrorMessage);
            return;
        }

        if (!file || !Object.keys(file).length) {

            if (!vscode.window.activeTextEditor && !vscode.window.activeTextEditor.document.uri) {

                vscode.window.showErrorMessage(noFileSelectedErrorMessage);
                return;
            }
            else {
                file = vscode.window.activeTextEditor.document.uri;
            }
        }
        
        netSuiteBl.uploadFileToNetSuite(file);
    });`

**Comment by silverl** [comment]
Would you please express the intent of this change in words? I'm not sure I understand it. I'm not familiar with VS Code extension coding. I'm guessing Object holds some globals and you're looking for a file object in the global collection?

Are you sure this should be an OR and not an AND &&?

**Comment by wym89** [comment]
@silverl  when i did the ctrl+u shortcut 'file' was an empty object  and was not getting into the `if(!file)` 
`!Object.keys(file).length`  checks if its an empty object

**Comment by silverl** [comment]
@wym89 Added your suggested change, thanks!

**Pull request merged**
