### PR TITLE
Adding the commands to the editor

### PR DESCRIPTION
**Pull request by paul7337**
Haven't contributed much to many projects, so hopefully, this is the correct way to suggest something that might be a nice feature.
Brilliant extension btw, thanks!

### CODE REVIEW

**Comment by silverl** [comment]
On second thought, looks like those context choices will only show up for javascript files. There are many other kinds of files for which we might want those context menus to show up. Basically, I think for any MIME type or file extension that one might find in the File Cabinet, it'd be nice to have the menu.

**Comment by paul7337** [comment]
Hi Larry, 

Good point on the type filtering. 
What about just removing the 'when' property rather than trying some kind of advanced filter for multiple types? 

` {
              "command": "netsuite-upload.downloadFile",
              "group": "netsuite"
}`

**Comment by silverl** [comment]
Sorry I haven't gotten back to you. Yes, I agree with that approach.

**Comment by paul7337** [comment]
Hi Larry, 

I removed the filtering from the package.json. Sorry, took a while so get back around to it. 

Thanks,
Paul

**Pull request merged**
